---
- name: Setup Docker and run a web application
  hosts: localhost
  become: yes
  tasks:
    - name: Ensure Docker is installed
      yum:
        name: docker
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started

    - name: Pull the Nginx Docker image
     community.docker.docker_image:
        name: nginx tag: latest
        state: present

    - name: Run Nginx container
      docker_container:
        name: my-nginx
        image: nginx
        state: started
        published_ports:
          - "80:80"
